# Generated by Django 5.0.3 on 2024-04-25 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10, verbose_name='Preço')),
                ('categoria', models.ForeignKey(help_text='Categoria do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='padarias.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome da cesta', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da cesta', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço da cesta', max_digits=10, verbose_name='Preço')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('M', 'Médio'), ('P', 'Premium')], default='B', help_text='Nível da cesta', max_length=1, verbose_name='Nível')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da cesta', null=True, upload_to='cestas', verbose_name='Imagem')),
                ('produtos', models.ManyToManyField(help_text='Produtos da cesta', related_name='cestas', to='padarias.produto', verbose_name='Produtos')),
            ],
        ),
    ]
