# Generated by Django 5.0.3 on 2024-04-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da categoria', null=True, verbose_name='Descrição'),
        ),
    ]
