# Generated by Django 5.0.3 on 2024-05-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da cesta', null=True, verbose_name='Descrição'),
        ),
    ]
