# Generated by Django 5.0.3 on 2024-04-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0002_categoria_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
