# Generated by Django 5.0.3 on 2024-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0003_cesta_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Data de término da assinatura', null=True, verbose_name='Data de término'),
        ),
    ]
