# Generated by Django 5.0.3 on 2024-04-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0004_produto_cesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='descricao',
        ),
    ]
