# Generated by Django 5.0.3 on 2024-05-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0006_padaria_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do remetente', max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Email do remetente', max_length=254, verbose_name='Email')),
                ('mensagem', models.TextField(help_text='Mensagem do email', verbose_name='Mensagem')),
            ],
        ),
    ]
