# Generated by Django 5.0.3 on 2024-05-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0007_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data de início da assinatura', verbose_name='Data de início')),
                ('data_fim', models.DateField(help_text='Data de término da assinatura', verbose_name='Data de término')),
                ('observacao', models.TextField(blank=True, help_text='Observação da assinatura', null=True, verbose_name='Observação')),
                ('cesta', models.OneToOneField(help_text='Cesta da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='padarias.cesta', verbose_name='Cesta')),
                ('user', models.OneToOneField(help_text='Usuário da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
